### ISSUE TITLE
Add an iPhone app

### ISSUE THREAD

**Issue by roydbt** [tvler/streetpass#37]
Basically the title. Make the Safari app downloadable from the iPhone App Store.

**Comment by tvler** [comment]
Hello! I'm closing this in favor of https://github.com/tvler/streetpass/discussions/36

This is gonna take a large amount of eng work, i'm going to think for a bit on the roadmap of this product and what features would best benefit the most users. this is still 100% on the table and very interesting to me. just need to think more!
