### ISSUE TITLE
[Feature Request] Right-click copy profile URLs and/or copy URL icon

### ISSUE THREAD

**Issue by todrobbins** [tvler/streetpass#44]
First of all: thank you for an amazing little extension! Secondly, it would improve the UX if we could right-click copy profile URLs and/or have a copy URL icon to quickly share the link instead of having to open it first.

I can take a look at the code but I'd appreciate it if someone else has the time to implement.

Thanks again!

**Comment by tvler** [comment]
Hi! This is a good idea. I think all we’d need to do is start using normal <a> elements with hrefs for this right click copy url pattern to work as expected. I can do this soon, but feel free to try out if your interested!

**Comment by tvler** [comment]
https://github.com/tvler/streetpass/assets/4934193/6e5b0011-3d16-4663-b087-2e13946bfdd1

this UX is gonna be in the next version!

**Comment by todrobbins** [comment]
Thanks @tvler, this is great!
