### ISSUE TITLE
GitHub Profile Social Links not recognized 

### ISSUE THREAD

**Issue by drmaxx** [tvler/streetpass#5]
The Github Link in the Profile is defined as
`<a rel="nofollow me" class="Link--primary" href="https://server.tld/@user">@user@server.tld</a>`
and is not recognized by StreetPass.

It would be great if I could collect these links as well.

Thanks for a great Browser extension

**Comment by Ciantic** [comment]
It works for me at the moment:

![image](https://user-images.githubusercontent.com/64731/217647641-8dfde9b4-3e76-4ee7-a3f5-ee77b8714e6b.png)

Went to your GitHub page.

**Comment by tvler** [comment]
Sometimes if the mastodon server is down it doesn’t track a valid link as a profile. Only bummer is I permanently cache that link as a “not-profile” value so it won’t be fixed next time you go to the page with the server working. This issue is on the roadmap for fixes!

**Comment by tvler** [comment]
Another thing it could have been: if you’ve seen this profile on another site already, it doesn’t get added a 2nd time to the list

**Comment by drmaxx** [comment]
> Another thing it could have been: if you’ve seen this profile on another site already, it doesn’t get added a 2nd time to the list

I assume that was the trap i fell into, it's working for me as well. 

Thank you for the clarification!
