### ISSUE TITLE
[Feature Request] Ability to set home instance so clicking a user opens on set instance

### ISSUE THREAD

**Issue by slrgt** [tvler/streetpass#60]
Love the Extension! It would be great to be able to set what my home instance is so when I click on a username it opens on my instance making it much easier to follow them

**Comment by slrgt** [comment]
Looks like this is actually already possible! Click on the extension, click the ... and then click on a preset like mastodo.social and then change the domain to your domain! 
![uE4fGpYZdR](https://github.com/tvler/streetpass/assets/114287507/3020073f-c2c9-4c8a-9c06-e73ac074eae7)

**Comment by tvler** [comment]
Nice! Glad you found that feature 😄
