### ISSUE TITLE
Mona.app links don't work

### ISSUE THREAD

**Issue by altano** [tvler/streetpass#65]
I tried the "Open Profiles With..." preset for Mona.app but it doesn't seem to work:

<img width="1676" alt="image" src="https://github.com/tvler/streetpass/assets/1009/44d83915-9fde-4941-8150-ef530b8462f4">

Thanks for this amazing extension, btw.

**Comment by tvler** [comment]
Oh man, yea looks like Mona changed their deeplinking url scheme in the most recent update. will try to figure out what the new url should be

**Comment by tvler** [comment]
asked here https://mastodon.social/@tvler/112073570826506321

**Comment by tvler** [comment]
Hi it looks like Mona's recent update fixed this issue! Thanks for bringing to my attention 😄
